name: Makefile CI

on:
  push:
    tags: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install npm dependencies
      run: npm install

    - name: Check code with eslint
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/node_modules/.bin"
        make eslint

    - name: APT update
      run: sudo apt-get update

    - name: Install intltool and gettext
      run: sudo apt-get install -y intltool gettext

    - name: Install libglib2.0-dev
      run: sudo apt-get install -y libglib2.0-dev

    - name: Install gnome-shell
      run: sudo apt-get install -y gnome-shell --no-install-recommends

    - name: Generate extension zip
      run: make build

    - name: Generate extension pot
      run: make potfile

    - name: Get release informations
      run: |
        echo "release_subject=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF/refs\/tags\//})" >> $GITHUB_ENV
        git tag -l --format='%(contents:body)' ${GITHUB_REF/refs\/tags\//} > releaseBody.md

    - name: Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        artifacts: "nasa_apod@elinvention.ovh.zip,nasa_apod@elinvention.ovh.pot"
        draft: false
        prerelease: false
        name: ${{ env.release_subject }}
        bodyFile: releaseBody.md
