name: Makefile CI

on:
  push:
    tags: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install npm dependencies
      run: npm install

    - name: Check code with eslint
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/node_modules/.bin"
        make eslint

    - name: APT update
      run: sudo apt-get update

    - name: Install intltool
      run: sudo apt-get install -y intltool

    - name: Install libglib2.0-dev
      run: sudo apt-get install -y libglib2.0-dev

    - name: Install gnome-shell
      run: sudo apt-get install -y gnome-shell --no-install-recommends

    - name: Generate extension zip
      run: make build

    - name: Get release informations
      run: |
        echo "subject=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF/refs\/tags\//})" >> $GITHUB_ENV
        {
          echo 'body<<EOF'
          git tag -l --format='%(contents:body)' ${GITHUB_REF/refs\/tags\//}
          echo EOF
        } >> $GITHUB_ENV

    - name: Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        name: ${{ env.release_subject }}
        body: ${{ env.release_body }}

    - name: Upload zip to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: nasa_apod@elinvention.ovh.zip
        asset_name: nasa_apod@elinvention.ovh.zip
        asset_content_type: application/zip

